## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
dist: bionic
env:
  - JULIA_COPY_STACKS=0
  - JULIA_COPY_STACKS=1
before_install:
  - source ${TRAVIS_BUILD_DIR}/test/windows_java.sh
julia:
  - 1.0
  - 1
  - nightly
notifications:
  email: false
git:
  depth: 99999999
jobs:
  include:
  - julia: 1
    env: JULIA_COPY_STACKS=1 JAVA_HOME=/usr/local/lib/jvm/openjdk8
    os: linux
  - julia: 1
    env: JULIA_COPY_STACKS=1 JAVA_HOME=/usr/local/lib/jvm/openjdk11
    os: linux
  - julia: 1
    env: JULIA_COPY_STACKS=1
    os: osx
    osx_image: xcode9.3
  - julia: 1
    env: JULIA_COPY_STACKS=0 JAVA_PKG=openjdk8
    os: windows
  exclude:
  - os: linux
    env: JULIA_COPY_STACKS=0
  - os: osx
    env: JULIA_COPY_STACKS=0
  - julia: 1.0
    env: JULIA_COPY_STACKS=0
  - julia: 1.0
    os: windows
    env: JULIA_COPY_STACKS=1
  - os: windows
    env: JULIA_COPY_STACKS=1
  allow_failures:
  - julia: nightly


## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("BioformatsLoader"); Pkg.test("BioformatsLoader"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("BioformatsLoader")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BioformatsLoader")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
